// get all persons
GET http://localhost:3001/api/persons/
###


//get a person
GET http://localhost:3001/api/persons/60243c57e44d704c6af4837b

###
// delete a person
DELETE http://localhost:3001/api/persons/60243c57e44d704c6af4837b
###


//post a person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Nika T",
    "number": "877889"
}